<?php
/**
 * This file is part of the FIREGENTO project.
 *
 * FireGento_GermanSetup is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License version 3 as
 * published by the Free Software Foundation.
 *
 * This script is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
 *
 * PHP version 5
 *
 * @category  FireGento
 * @package   FireGento_GermanSetup
 * @author    FireGento Team <team@firegento.com>
 * @copyright 2012 FireGento Team (http://www.firegento.de). All rights served.
 * @license   http://opensource.org/licenses/gpl-3.0 GNU General Public License, version 3 (GPLv3)
 * @version   $Id:$
 * @since     0.1.0
 */
/**
 * Template for tax display and shipping cost link
 *
 * @category  FireGento
 * @package   FireGento_GermanSetup
 * @author    FireGento Team <team@firegento.com>
 * @copyright 2012 FireGento Team (http://www.firegento.de). All rights served.
 * @license   http://opensource.org/licenses/gpl-3.0 GNU General Public License, version 3 (GPLv3)
 * @version   $Id:$
 * @since     0.1.0
 */

/**
 * @var $this FireGento_GermanSetup_Block_Catalog_Product_Price_Info
 */

/**
 * Block for price info which is displayed comma-separated
 */
?>

<?php
    $texts = $this->getInfoTexts();
?>
<span class="price-info">
<?php
    $firstLoop = true;
    foreach($texts as $key => $text):
        if ($firstLoop): ?>
            <span class="<?php echo $key ?>"><?php echo ucfirst($text) ?></span>
        <?php else: ?>
            <span class="tax-separator">, </span><span class="<?php echo $key ?>"><?php echo $text ?></span>
        <?php endif;
        $firstLoop = false;
    endforeach
?>
</span>