<?php
/**
 * This file is part of the FIREGENTO project.
 *
 * FireGento_GermanSetup is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License version 3 as
 * published by the Free Software Foundation.
 *
 * This script is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
 *
 * PHP version 5
 *
 * @category  FireGento
 * @package   FireGento_GermanSetup
 * @author    FireGento Team <team@firegento.com>
 * @copyright 2012 FireGento Team (http://www.firegento.de). All rights served.
 * @license   http://opensource.org/licenses/gpl-3.0 GNU General Public License, version 3 (GPLv3)
 * @version   $Id:$
 * @since     0.1.0
 */
/**
 * Checkout Agreements
 *
 * @category  FireGento
 * @package   FireGento_GermanSetup
 * @author    FireGento Team <team@firegento.com>
 * @copyright 2013 FireGento Team (http://www.firegento.de). All rights served.
 * @license   http://opensource.org/licenses/gpl-3.0 GNU General Public License, version 3 (GPLv3)
 * @version   $Id:$
 * @since     1.2.2
 */

/**
 * @var $this FireGento_GermanSetup_Block_Checkout_Agreements
 */

/** @var $helper FireGento_GermanSetup_Helper_Data */
$helper = Mage::helper('germansetup');
$agreements = $this->getAgreements();
?>

<?php if (!$agreements) return; ?>

<form action="" id="checkout-agreements" onsubmit="return false;">
<ol class="checkout-agreements">
<?php foreach ($agreements as $agreement): ?>
    <?php
        $checkBoxLabel = $agreement->getIsHtml() ? $agreement->getCheckboxText() : $this->htmlEscape($agreement->getCheckboxText());
        $matches = array();
        if($matched = preg_match('/\[([^\]]*)\]/i', $checkBoxLabel, $matches)) {
            $linkMarkup = $matches[0];
            $linkLabel  = $matches[1];
            $clickableLink = '<a href="'.$this->getUrl('germansetup/frontend/agreements', array('id' => $agreement->getId())).'" target="agreement-'.$agreement->getId().'" onclick="window.open(\''.$this->getUrl('germansetup/frontend/agreements', array('id' => $agreement->getId())).'\', \'agreement-'.$agreement->getId().'\', \'width=600,height=600,left=0,top=0,location=no,status=yes,scrollbars=yes,resizable=yes\').focus(); return false;">'.$linkLabel.'</a>';
            $checkBoxLabel = str_replace($linkMarkup, $clickableLink, $checkBoxLabel);
        }
    ?>
    <li>
        <p class="agree">
            <?php if($agreement->getIsRequired()): ?>
                <input type="checkbox" id="agreement-<?php echo $agreement->getId()?>" name="agreement[<?php echo $agreement->getId()?>]" value="1" title="<?php echo $this->htmlEscape($agreement->getCheckboxText()) ?>" class="checkbox" />
            <?php endif; ?>
            <label <?php if($agreement->getIsRequired()): ?>for="agreement-<?php echo $agreement->getId()?>"<?php endif; ?>>
				<?php echo $checkBoxLabel ?>
			</label>
			<?php if(!$matched): ?>
				<a href="<?php echo $helper->getAgreementUrl($agreement) ?>" onclick="window.open(this.href, '', 'width=600,height=600,left=0,top=0,location=no,status=yes,scrollbars=yes,resizable=yes').focus(); return false;"><?php echo $this->__('[Show]') ?></a>
			<?php endif; ?>
        </p>
    </li>
<?php endforeach ?>
</ol>
</form>
