<?php
/**
 * This file is part of the FIREGENTO project.
 *
 * FireGento_GermanSetup is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License version 3 as
 * published by the Free Software Foundation.
 *
 * This script is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
 *
 * PHP version 5
 *
 * @category  FireGento
 * @package   FireGento_GermanSetup
 * @author    FireGento Team <team@firegento.com>
 * @copyright 2012 FireGento Team (http://www.firegento.de). All rights served.
 * @license   http://opensource.org/licenses/gpl-3.0 GNU General Public License, version 3 (GPLv3)
 * @version   $Id:$
 * @since     0.1.0
 */
/** @var $this Mage_Core_Block_Template */
?>
<?php $_item = $this->getParentBlock()->getItem() ?>
<?php if ($_attributes = Mage::helper('germansetup/checkout_data')->getAddtionalAttributes()):?>
<div class="additional-information">
    <dl class="item-options">
        <?php foreach ($_attributes as $_attribute) : ?>
        <dt><?php echo $this->htmlEscape($_attribute->getAttributeLabel()) ?></dt>
         <?php $attribute_value = $_attribute->getFrontendInput() == 'select' ? $_item->getProduct()->getAttributeText($_attribute->getAttributeCode()) : $_item->getProduct()->getData($_attribute->getAttributeCode())?>
        <dd class="truncated"><?php echo $this->escapeHtml($attribute_value) ?></dd>
        <?php endforeach; ?>
    </dl>
</div>
<?php endif;?>

